### ISSUE TITLE
about:文章上そろえ

### ISSUE THREAD

**Issue by atsu0131** [creative-closet/urushitoki#342]
![スクリーンショット 2021-12-22 23 55 44](https://user-images.githubusercontent.com/26783386/147111748-c850c2fb-e53a-4c4a-9fed-16b85767ec54.png)

**Comment by aodesuyo** [comment]
ブランチ作成してしまいましたが、管理画面から上揃えを選択することによって(コードを編集せずとも)位置を変えられると思います。
developブランチの管理画面から編集しておけばよろしいでしょうか？
↓管理画面
![image](https://user-images.githubusercontent.com/64908452/147560188-9b7b82b2-a20c-43ea-9cf8-cad6e4df7ca7.png)
↓上揃え選択後
![urushitokilocal local_about__preview_id=144e](https://user-images.githubusercontent.com/64908452/147560361-4a0224b4-5578-4d48-ac3e-0ae6d6b943ef.png)
