### ISSUE TITLE
金継ぎ：画像の端の白いところの修正

### ISSUE THREAD

**Issue by riel-maker** [creative-closet/urushitoki#452]

**Comment by atsu0131** [comment]
右端の余白をなくす
![スクリーンショット 2022-01-19 21 46 51](https://user-images.githubusercontent.com/26783386/150133544-7e819f62-919a-4a50-a534-5cd30eadd5d1.png)

パディングで下に余白を空ける
![スクリーンショット 2022-01-19 21 46 54](https://user-images.githubusercontent.com/26783386/150133599-db6ee1f8-b831-4c6b-a1dc-faf47704aa9d.png)
